config/routes.rb
Rails.application.routes.draw do
 
  get 'comment/store'

  get 'main/index'
  
  root 'main#index'
  
  get 'main/hypcasual'

  get 'main/details'
  
  post 'comment/store'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def store
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to '/'
  end
  
  private
    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        #render plain: params
        # @article = Article.find(params[sarticle_id])
        # @comment = @article.coments.create(comment_params)
        # redirect_to article_path(@article)
    end

private
    def comment_params
        params.require(:comment).permit(:commenter, :body)
    end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
      @comments = Comment.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/comment/store.html.erb
<h1>Comment#store</h1>
<p>Find me in app/views/comment/store.html.erb</p>

app/views/comments/_comment.html.erb
<p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
</p>

<p>
    <strong>Comment:</strong>
    <%= comment.body %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/details.html.erb
<head>
	<title>Details about Tales Dash</title>
	<link type="text/css" rel="stylesheet" href="/style.css"/>
	<meta charset="utf-8"/>
</head>
	
<body>
	<div class="titlebox">
		<h1>테일즈 대쉬 상세 정보</h1>
	</div>
	
	<div class="contents">
		<div class="contentbox-single">
			<p>테일즈 대쉬에는 여러 요소들이 존재합니다.
			게임 속에서 마주치게 될 환경과 오브젝트들에는 다음과 같은 것들이 있습니다.</p>
		</div>
		
		
		<div class = "list-container">
			<div class="dual-container">
			
				<div class="contentbox-dual-left">
					<img class = "smallImg" src="img_tile.png" />
				</div>
			
			
				<div class="contentbox-dual-right">
					<ul type = "circle">
						<li><strong>타일</strong>
							<p>캐시가 탐험하는 월드들에 존재하는 길들입니다. 캐시는 여러 월드들에 있는 보석과 별들을 모으기 위해 이 타일들 위를 달리며 월드들을 탐험합니다. 하지만 삐끗해서 떨어진다면... 상상도 하기 싫군요. 캐시를 도와서 떨어지지 않고 월드들을 탐험할 수 있게 해줘야해요!
							</p>
						</li>
					</ul>

				</div>
			
			</div>

			<div class="dual-container">
			
				<div class="contentbox-dual-left">
					<%= image_tag("img_narrow.png", :alt => "image explanation", :class => "smallImg") %>
				</div>
			
			
				<div class="contentbox-dual-right">
					<ul type = "circle">
													
						<li><strong>좁은 타일</strong>
							<p>일반 타일보다 더 폭이 좁은 타일들입니다. 보다 정확하게 가운데로 캐시를 달리게 하지 않으면 떨어지겠죠? 조심하세요!
							</p>
						</li>
					</ul>

				</div>
			</div>

			<div class="dual-container">
			
				<div class="contentbox-dual-left">
					<%= image_tag("img_rabbit.png", :alt => "image explanation", :class => "smallImg") %>
				</div>
			
			
				<div class="contentbox-dual-right">
					<ul type = "circle">
						<li><strong>토끼 타일</strong>
							<p>귀엽게 보이는 타일이지만 그 기능은 마냥 귀엽지만은 않습니다. 캐시에게 마법의 토끼띠를 씌우거든요. 마법의 토끼띠까지 했는데 빠르게 달리지 않을 수는 없잖아요?
							</p>
						
						</li>
					</ul>

				</div>
			</div>

			<div class="dual-container">
			
				<div class="contentbox-dual-left">
					<%= image_tag("img_gate.jpg", :alt => "image explanation", :class => "smallImg") %>
				</div>
			
			
				<div class="contentbox-dual-right">
					<ul type = "circle">
						<li><strong>차원문</strong>
							<p>월드와 월드를 이어주는 차원문입니다. 여기를 통과하면 캐시는 다른 지난 스테이지를 클리어하고 다음 스테이지로 넘어가게 됩니다.
							</p>
						
						</li>
					</ul>

				</div>
			</div>

			<div class="dual-container">
			
				<div class="contentbox-dual-left">
					<%= image_tag("img_jewel.png", :alt => "image explanation", :class => "smallImg") %>
				</div>
			
			
				<div class="contentbox-dual-right">
					<ul type = "circle">
						<li><strong>보석</strong>
							<p>월드에 존재하는 보물입니다. 캐시의 목표는 이 보석들을 모두 모으는 것! 모든 보석들을 모으면 왕관도 얻을 수 있습니다.
							</p>
						
						</li>
						
					</ul>

				</div>
			</div>

			<div class="dual-container">
			
				<div class="contentbox-dual-left">
					<%= image_tag("img_star.png", :alt => "image explanation", :class => "smallImg") %>
				</div>
			
			
				<div class="contentbox-dual-right">
					<ul type = "circle ">
						<li><strong>별</strong>
							<p>보석과 같이 월드에 존재하는 보물입니다. 보석보다 수는 적지만 그만큼 희귀하고 중요한 보물들이죠. 각 스테이지에는 별이 세 개씩 있습니다.
							</p>
						
						</li>
						
					</ul>

				</div>
				
			</div>	
			
		</div "list container">
	</div>
	
	<div class = "endbox">
		
		<p> <%= link_to "처음으로", main_index_path %>  </p>
	</div>
	
</body>

app/views/main/hypcasual.html.erb
<head>
	<title> What are Hypercasual Games? </title>
	<link type="text/css" rel="stylesheet" href="/style.css"/>
	<meta charset="utf-8"/>
</head>

<body>
	<div class = "titlebox" >
		<h1> 하이퍼캐주얼 게임이란? </h1>
	</div>	
	
	<div class="contents">	
		<div class="contentbox-single">
			<p>하이퍼캐주얼은 이름 그대로 매우<em>(Hyper)</em> 가벼운 <em>(Casual)</em> 게임들을 아우르는 장르입니다. 하이퍼캐주얼 장르는 스마트폰 시대를 거슬러 핸드폰, 혹은 흔히 말하는 피쳐폰 시절까지 올라갑니다. 그 당시의 핸드폰은 지금처럼 강력한 연산능력이나 그래픽 성능을 가지지 못했기 때문에 지금보다 구현할 수 있는 멀티미디어 컨텐츠의 수준도 심플했습니다. 그래서 당시의 게임들은 리소스의 제약이 많았고, 따라서 매우 단순한 게임들이 많았습니다. 마치 퐁<em>(Pong)</em> 같은 컴퓨터 게임 역사의 초기 게임들처럼 말이죠.
			</p>
		</div>
		
		<div class = "dual-container">
			<div class="contentbox-dual-mono">
				<img class = "bigImg" src="https://noyouare.lixlink.com/wp-content/uploads/2013/01/Pong-game.jpg" style="height:250px;width:auto;" />
				
				<p align = "center"> <em> 초창기 컴퓨터 게임 "Pong" </em>
				</p>
			
			</div>
			
			<div class="contentbox-dual-mono">
				<img class = "bigImg" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.ytimg.com%2Fvi%2FqPiaPKNelc0%2Fmaxresdefault.jpg&f=1&nofb=1";  style="height:250px;width:auto;" />
			
				<p align = "center"> <em>인기 모바일 게임 "Helix Jump" </em>
				</p>
				
			</div>
		
		</div>		
		
		<div class = "contentbox-single">
			<p>그래픽이 단순하고 매커니즘이 심플해도 게임의 재미가 바래지는 않습니다. 오히려 외향과 복잡성을 벗어나 가장 본질적인 재미요소를 제공한다는 점에서는 가장 있는 그대로의 게임을 대표한다고도 할 수 있겠죠. 그리하여 기기 성능이 좋아진 현재 스마트폰 시대에 와서도 하이퍼캐주얼 게임은 꾸준히, 그리고 많이 만들어지고 소비되고 있습니다. 
			</p>
		</div>
	</div>

	<div class="endbox">	
		
		
		<p> <%= link_to "처음으로", main_index_path %>  </p>
	</div>
</body>

app/views/main/index.html.erb
<head>
	<title> Introducing Tales Dash! </title>
	<link type="text/css" rel="stylesheet" href="/style.css"/>
	<meta charset="utf-8"/>
</head>

<body>
	
	<div class = "titlebox">
		<h1>테일즈 대쉬를 소개합니다! </h1>
	</div>
	
	<div class = "contents">
		
		<div class = "dual-container">
		
			<div class = "contentbox-dual-left">
				<img class = "smallImg" src="https://lh3.googleusercontent.com/jcja4htRwN5pda9KzZ65RjIbaEQph4_0dR95_-EP3p59u0PY65zfg0OLJ84Zubr2nQ=s360" />
				
			</div>
	
			<div class = "contentbox-dual-right" id= "introdescription"> 			
				<p>테일즈 대쉬 (<strong>Tales Dash</strong>)는 모바일 게임 회사 <span style="color:#E4007F"><strong>알로하팩토리</strong></span>에서 개발한 모바일 게임입니다. 4월 2일에 출시된 따끈따끈한 신작이지요. 본 페이지에서는 테일즈 대쉬의 기획자인 제가 테일즈 대쉬를 소개하는 시간을 가져보도록 하겠습니다.
				</p>
			</div>
		</div>	
		
		
		<div class = "contentbox-single">
			<p>테일즈 대쉬는 간단한 <%= link_to "하이퍼캐주얼 장르", main_hypcasual_path %>의 게임으로, 주인공인 트레져 헌터 캐시를 조작해서 떨어지지 않고 여러 월드들을 모험하는 게임입니다. 테일즈 대쉬는 하이퍼캐주얼 게임답게 매우 간단한 조작을 가지고 있습니다. 탭. 오직 탭 뿐이지요.
			</p>
			
			<p>게임의 진행은 아래와 같습니다.
			</p>
		</div>
		
		<div class = "dual-container">
			<div class = "contentbox-dual-left">
				<img class = "bigImg" src="https://lh3.googleusercontent.com/zHnx4uoCe-IGmfTKMRCRmAMVV1VauIpQ6Ff8QEJ9P6QDfPVfKcvW25cGHGoneDJ38g=w3072-h1500"  />
			</div>
			
			<div class = "contentbox-dual-right">
				<ol type="1" >
					<li>게임을 시작하면 캐시가 길을 따라 달려나갑니다.</li>
					<li>방향을 틀거나 점프를 해야하는 순간이 왔을 때 탭을 하면 상황에 맞는 액션을 취할 수 있습니다.</li>
					<li>앞의 길을 잘 살피며 적절한 타이밍에 탭 액션을 성사시켜 캐시를 추락시키지 않고 계속 달리게 합니다.</li>
					<li>스테이지를 클리어하면 다음 스테이지인 다른 월드로 이어지며 게임은 계속됩니다.</li>
					<li>???</li>
					<li>PROFIT!</li>
				</ol>
			</div>
		</div>
	
		<div class = "contentbox-single">
			<p>이처럼 매우 간단한 게임 방식을 가지고 있지만, 게임 내에서 등장하는 여러가지 환경과 수집요소들은 직관적이고도 재미있는 조작법과 맞물려 나름의 깊이있는 경험을 할 수 있게 해줍니다. 보다 세부적인 게임 설명은 <%= link_to "다음페이지", main_details_path %> 에서 알아보실 수 있습니다.
			</p>
			
		</div>
		
		
		
		<div class = "contentbox-single" id="comment_section">
            <h2>게임에 대한 코멘트를 남겨주세요!</h2>
            <% @comments.each do |comment| %>
                <p><%= comment.comment %></p>
            <% end %>
            
            <%= form_for :comment, url: '/comment/store', local: true do |form| %>
            <div class="form-group">
                <%= form.label :comment %>
                <%= form.text_field :comment %>
                <%= form.submit %>
            </div>

            <% end %>
        </div>  
		
	</div>
	
	<div class = "endbox">
		
		<p style = "font-size:20px; font-family:Sans">Tales Dash가 궁금하시다면? <a href="https://play.google.com/store/apps/details?id=kr.co.alohacorp.talesdash&hl=en_us"> 다운로드하기!</a>(google play only)</p>
	</div>

</body>